-- holiday 
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-01-01', 1, '신정', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-01-31', 1, '설날', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-02-01', 1, '설날', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-02-02', 1, '설날', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-03-01', 1, '삼일절', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-03-09', 1, '대통령선거', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-05-05', 1, '어린이날', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-05-08', 1, '부처님오신날', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-06-01', 1, '전국동시지방선거', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-06-06', 1, '현충일', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-08-15', 1, '광복절', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-09-09', 1, '추석', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-09-10', 1, '추석', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-09-11', 1, '추석', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-09-12', 1, '추석', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-10-03', 1, '개천절', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-10-09', 1, '한글날', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-10-10', 1, '한글날', 0, NOW(), NOW());
INSERT INTO ohnae3.CHLORIS_HOLIDAY(DAY_DATE, HOLIDAY_CODE, HOLIDAY_NAME, PRICE, CREATE_DATE, UPDATE_DATE) VALUES('2022-12-25', 1, '크리스마스', 0, NOW(), NOW());

