-- ohnae3.CHLORIS_FAQ definition

CREATE TABLE `CHLORIS_FAQ` (
  `FAQ_NUMBER` int(15) NOT NULL AUTO_INCREMENT COMMENT 'FAQ',
  `QUESTION` varchar(255) NOT NULL,
  `ANSWER` varchar(255) NOT NULL,
  `PRIORITY` int(4) DEFAULT NULL,
  `CREATE_DATE` datetime NOT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  PRIMARY KEY (`FAQ_NUMBER`),
  UNIQUE KEY `FAQ_NUMBER` (`FAQ_NUMBER`)
) ENGINE=MyISAM AUTO_INCREMENT=20 DEFAULT CHARSET=utf8;

-- ohnae3.CHLORIS_HOLIDAY definition

CREATE TABLE `CHLORIS_HOLIDAY` (
  `DAY_DATE` date NOT NULL COMMENT '날짜',
  `HOLIDAY_CODE` tinyint(4) NOT NULL COMMENT '휴일코드 1: 휴일 2:특정일',
  `HOLIDAY_NAME` varchar(255) NOT NULL,
  `PRICE` int(11) DEFAULT NULL COMMENT '가격',
  `CREATE_DATE` datetime NOT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  PRIMARY KEY (`DAY_DATE`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- ohnae3.CHLORIS_NOTICE definition

CREATE TABLE `CHLORIS_NOTICE` (
  `NOTICE_NUMBER` int(11) NOT NULL AUTO_INCREMENT,
  `SUBJECT` varchar(255) NOT NULL,
  `CONTENT` varchar(255) NOT NULL,
  `CREATE_DATE` datetime NOT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  PRIMARY KEY (`NOTICE_NUMBER`),
  UNIQUE KEY `NOTICE_NUMBER` (`NOTICE_NUMBER`)
) ENGINE=MyISAM AUTO_INCREMENT=20 DEFAULT CHARSET=utf8;

-- ohnae3.CHLORIS_QNA definition

CREATE TABLE `CHLORIS_QNA` (
  `QNA_NUMBER` int(15) NOT NULL AUTO_INCREMENT,
  `MEMBER_NAME` varchar(50) NOT NULL,
  `MEMBER_PHONE` varchar(50) NOT NULL,
  `MEMBER_EMAIL` varchar(200) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `SUBJECT` varchar(150) NOT NULL,
  `CONTENT` varchar(255) NOT NULL,
  `CREATE_DATE` datetime NOT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  PRIMARY KEY (`QNA_NUMBER`)
) ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=utf8;

-- ohnae3.CHLORIS_QNA_REPLY definition

CREATE TABLE `CHLORIS_QNA_REPLY` (
  `QNA_NUMBER` int(15) NOT NULL,
  `CONTENT` varchar(255) NOT NULL,
  `CREATE_DATE` datetime NOT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  PRIMARY KEY (`QNA_NUMBER`),
  KEY `QNA_NUMBER` (`QNA_NUMBER`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

-- ohnae3.CHLORIS_RESERVATION definition

CREATE TABLE `CHLORIS_RESERVATION` (
  `RESERVATION_NUMBER` int(15) NOT NULL AUTO_INCREMENT COMMENT '예약번호',
  `RESERVATION_DATE` date NOT NULL COMMENT '예약일',
  `ROOM_NUMBER` int(11) NOT NULL COMMENT '객실번호',
  `PRICE` int(11) NOT NULL COMMENT '가격',
  `STATUS_CODE` tinyint(4) NOT NULL COMMENT '상태코드 1:예약 2:예약완료 3:예약취소',
  `MEMBER_NAME` varchar(50) NOT NULL COMMENT '회원명',
  `MEMBER_PHONE` varchar(50) NOT NULL COMMENT '회원전화번호',
  `MEMBER_EMAIL` varchar(200) NOT NULL COMMENT '회원이메일',
  `DESCRIPTION` varchar(255) DEFAULT NULL COMMENT '비고',
  `ADD_COUNT_1` int(11) DEFAULT NULL COMMENT '추가인원',
  `ADD_COUNT_2` int(11) DEFAULT NULL COMMENT '바베큐추가수',
  `ADD_COUNT_3` int(11) DEFAULT NULL COMMENT '온수추가수',
  `CREATE_DATE` datetime NOT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  PRIMARY KEY (`RESERVATION_NUMBER`,`RESERVATION_DATE`),
  KEY `ROOM_NUMBER` (`ROOM_NUMBER`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=40 DEFAULT CHARSET=utf8;

-- ohnae3.CHLORIS_ROOM definition

CREATE TABLE `CHLORIS_ROOM` (
  `ROOM_NUMBER` int(11) NOT NULL AUTO_INCREMENT,
  `ROOM_NAME` varchar(100) NOT NULL,
  `ROOM_TYPE_CODE` tinyint(4) NOT NULL COMMENT '객실구분코드 1:일반',
  `ROOM_M2` tinyint(4) NOT NULL COMMENT '평수',
  `MIN_PERSONNEL` tinyint(4) NOT NULL COMMENT '기준인원',
  `MAX_PERSONNEL` tinyint(4) NOT NULL COMMENT '최대인원',
  `PRICE_1` int(11) NOT NULL COMMENT '비수기주중요금',
  `PRICE_2` int(11) NOT NULL COMMENT '비수기금요일요금',
  `PRICE_3` int(11) NOT NULL COMMENT '비수기주말요금',
  `PRICE_4` int(11) NOT NULL COMMENT '준성수기주중요금',
  `PRICE_5` int(11) NOT NULL COMMENT '준성수기금요일요금',
  `PRICE_6` int(11) NOT NULL COMMENT '준성수기주말요금',
  `PRICE_7` int(11) NOT NULL COMMENT '성수기주중요금',
  `PRICE_8` int(11) NOT NULL COMMENT '성수기금요일요금',
  `PRICE_9` int(11) NOT NULL COMMENT '성수기주말요금',
  `PRICE_10` int(11) NOT NULL COMMENT '극성수기주중요금',
  `PRICE_11` int(11) NOT NULL COMMENT '극성수기금요일요금',
  `PRICE_12` int(11) NOT NULL COMMENT '극성수기주말요금',
  `PRICE_ADD_1` int(11) NOT NULL COMMENT '인원초과요금',
  `PRICE_ADD_2` int(11) NOT NULL COMMENT '바베큐요금',
  `PRICE_ADD_3` int(11) NOT NULL COMMENT '온수요금',
  `PRICE_ADD_4` int(11) DEFAULT NULL COMMENT '기타요금4',
  `PRICE_ADD_5` int(11) DEFAULT NULL COMMENT '기타요금5',
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `PRIORITY` tinyint(4) DEFAULT NULL COMMENT '우선순위',
  `CREATE_DATE` datetime NOT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  PRIMARY KEY (`ROOM_NUMBER`),
  UNIQUE KEY `ROOM_NAME` (`ROOM_NAME`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;



