SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS RIVERHILL_QNA_REPLY;
DROP TABLE IF EXISTS RIVERHILL_QNA;
DROP TABLE IF EXISTS RIVERHILL_RESERVATION;
DROP TABLE IF EXISTS RIVERHILL_ROOM;




/* Create Tables */

CREATE TABLE RIVERHILL_QNA
(
	QNA_NUMBER int NOT NULL AUTO_INCREMENT,
	MEMBER_NAME varchar(50) NOT NULL,
	MEMBER_PHONE varchar(50) NOT NULL,
	MEMBER_EMAIL varchar(100) NOT NULL,
	PASSWORD varchar(255) NOT NULL,
	SUBJECT varchar(150) NOT NULL,
	CONTENT varchar(255) NOT NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (QNA_NUMBER)
);


CREATE TABLE RIVERHILL_QNA_REPLY
(
	QNA_REPLY_NUMBER int NOT NULL AUTO_INCREMENT,
	QNA_NUMBER int NOT NULL,
	MEMBER_NAME varchar(50) NOT NULL,
	CONTENT varchar(255) NOT NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (QNA_REPLY_NUMBER, QNA_NUMBER)
);


CREATE TABLE RIVERHILL_RESERVATION
(
	RESERVATION_NUMBER int NOT NULL AUTO_INCREMENT,
	RESERVATION_DATE date NOT NULL,
	ROOM_NUMBER int NOT NULL,
	ROOM_STATUS_CODE tinyint NOT NULL,
	MEMBER_NAME varchar(50) NOT NULL,
	MEMBER_PHONE varchar(50) NOT NULL,
	PASSWORD varchar(255) NOT NULL,
	DESCRIPTION varchar(255),
	DATE_NUMBER tinyint NOT NULL,
	PERSONNEL_1 tinyint NOT NULL,
	PERSONNEL_2 tinyint DEFAULT 0 NOT NULL,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (RESERVATION_NUMBER, RESERVATION_DATE)
);


CREATE TABLE RIVERHILL_ROOM
(
	ROOM_NUMBER int NOT NULL,
	ROOM_NAME varchar(100) NOT NULL,
	ROOM_TYPE_CODE tinyint NOT NULL,
	ROOM_M2 tinyint NOT NULL,
	MIN_PERSONNEL tinyint NOT NULL,
	MAX_PERSONNEL tinyint NOT NULL,
	PRICE_1 tinyint NOT NULL,
	PRICE_2 tinyint NOT NULL,
	PRICE_3 tinyint NOT NULL,
	PRICE_4 tinyint NOT NULL,
	PRICE_5 tinyint NOT NULL,
	PRICE_6 tinyint NOT NULL,
	PRICE_7 tinyint NOT NULL,
	PRICE_8 tinyint NOT NULL,
	PRICE_9 tinyint NOT NULL,
	PRICE_ADD tinyint NOT NULL,
	DESCRIPTION varchar(255),
	PRIORITY tinyint,
	CREATE_DATE datetime NOT NULL,
	UPDATE_DATE datetime NOT NULL,
	PRIMARY KEY (ROOM_NUMBER),
	UNIQUE (ROOM_NUMBER),
	UNIQUE (ROOM_NAME)
);



/* Create Foreign Keys */

ALTER TABLE RIVERHILL_QNA_REPLY
	ADD FOREIGN KEY (QNA_NUMBER)
	REFERENCES RIVERHILL_QNA (QNA_NUMBER)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RIVERHILL_RESERVATION
	ADD FOREIGN KEY (ROOM_NUMBER)
	REFERENCES RIVERHILL_ROOM (ROOM_NUMBER)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



